-- =====================================================
-- Complément de contenu editable — La Perche Tendue V2
-- Insere les 71 blocs manquants (pages branchees mais vides)
-- A importer dans la base la_perche_tendue via phpMyAdmin
-- =====================================================
USE la_perche_tendue;

INSERT IGNORE INTO pages_contenu (page_slug, page_titre, bloc, contenu) VALUES
('accueil-services-titre', 'Accueil', 'services-titre', 'Ce que nous faisons'),
('accueil-service1-texte', 'Accueil', 'service1', 'Aide alimentaire : distribution de colis et épicerie solidaire pour les familles en difficulté.'),
('accueil-service2-texte', 'Accueil', 'service2', 'Accompagnement social : écoute, orientation et soutien dans les démarches du quotidien.'),
('accueil-service3-texte', 'Accueil', 'service3', 'Lien social : ateliers, événements et moments de partage ouverts à toutes et tous.'),
('accueil-actu-titre', 'Accueil', 'actu-titre', 'Nos actualités'),
('accueil-actu1-titre', 'Accueil', 'actu1-titre', 'Distribution alimentaire'),
('accueil-actu1-texte', 'Accueil', 'actu1-texte', 'Retrouvez nos permanences et distributions solidaires tout au long de la semaine dans nos épiceries.'),
('accueil-actu2-titre', 'Accueil', 'actu2-titre', 'Événements solidaires'),
('accueil-actu2-texte', 'Accueil', 'actu2-texte', 'Tout au long de l\'année, l\'association organise des temps forts pour créer du lien et récolter des soutiens.'),
('accueil-actu3-titre', 'Accueil', 'actu3-titre', 'Rejoignez les bénévoles'),
('accueil-actu3-texte', 'Accueil', 'actu3-texte', 'Vous avez un peu de temps ? Chaque coup de main compte. Contactez-nous pour participer à nos actions.'),
('accueil-perche-titre', 'Accueil', 'perche-titre', 'Pourquoi « La Perche Tendue » ?'),
('activites-intro', 'Nos activités', 'intro', 'L\'association mène de nombreuses actions de terrain pour accompagner les personnes en difficulté et renforcer le lien social sur le territoire.'),
('activites-alimentaire-titre', 'Nos activités', 'alimentaire-titre', 'Aide alimentaire'),
('activites-alimentaire-texte', 'Nos activités', 'alimentaire-texte', 'Distribution de colis et épicerie solidaire à prix réduits pour soutenir les familles au quotidien.'),
('activites-social-titre', 'Nos activités', 'social-titre', 'Accompagnement social'),
('activites-social-texte', 'Nos activités', 'social-texte', 'Écoute, orientation et aide dans les démarches administratives et l\'accès aux droits.'),
('activites-lien-titre', 'Nos activités', 'lien-titre', 'Lien social'),
('activites-lien-texte', 'Nos activités', 'lien-texte', 'Ateliers, rencontres et événements pour rompre l\'isolement et favoriser le partage.'),
('activites-parrainage-titre', 'Nos activités', 'parrainage-titre', 'Parrainage'),
('activites-parrainage-texte', 'Nos activités', 'parrainage-texte', 'Un dispositif de parrainage solidaire pour accompagner durablement les personnes qui en ont besoin.'),
('activites-culture-titre', 'Nos activités', 'culture-titre', 'Activités culturelles'),
('activites-culture-texte', 'Nos activités', 'culture-texte', 'Sorties, festivals et projets culturels ouverts à toutes et tous, pour cultiver la joie et l\'ouverture.'),
('activites-benevolat-titre', 'Nos activités', 'benevolat-titre', 'Bénévolat'),
('activites-benevolat-texte', 'Nos activités', 'benevolat-texte', 'Rejoignez une équipe engagée : votre temps et votre énergie font vivre nos actions solidaires.'),
('valeurs-intro', 'Valeurs', 'intro', 'Nos valeurs guident chacune de nos actions et donnent du sens à notre présence sur le terrain.'),
('valeurs-solidarite', 'Valeurs', 'solidarite', 'être présents auprès des plus fragiles, sans jugement, avec constance et générosité.'),
('valeurs-respect', 'Valeurs', 'respect', 'accueillir chaque personne dans sa dignité, quelle que soit sa situation.'),
('valeurs-engagement', 'Valeurs', 'engagement', 'agir concrètement et durablement, en tenant nos promesses envers les bénéficiaires.'),
('valeurs-bienveillance', 'Valeurs', 'bienveillance', 'écouter, accompagner et soutenir avec douceur et humanité.'),
('equipe-texte1', 'Équipe', 'texte1', 'Notre équipe réunit des bénévoles engagés, venus d\'horizons variés, unis par la même envie d\'aider.'),
('equipe-texte2', 'Équipe', 'texte2', 'Chacun apporte ses compétences et son temps pour accompagner au mieux les bénéficiaires.'),
('equipe-texte3', 'Équipe', 'texte3', 'Ensemble, nous faisons vivre les actions de l\'association au quotidien, dans un esprit d\'entraide.'),
('engagement-texte1', 'Engagement', 'texte1', 'Nous nous engageons à répondre aux besoins essentiels des personnes en difficulté avec dignité et respect.'),
('engagement-texte2', 'Engagement', 'texte2', 'Notre action s\'inscrit dans la durée : accompagner, soutenir et redonner confiance.'),
('engagement-texte3', 'Engagement', 'texte3', 'Chaque geste compte : ensemble, nous construisons une solidarité concrète et de proximité.'),
('contact-lens-adresse', 'Contact', 'lens-adresse', '56 rue Casimir Beugnet, 62300 Lens'),
('contact-lens-tel', 'Contact', 'lens-tel', '06 68 49 25 07'),
('contact-lens-horaires', 'Contact', 'lens-horaires', 'À COMPLÉTER — horaires d\'ouverture de l\'épicerie de Lens'),
('contact-arras-adresse', 'Contact', 'arras-adresse', '122 rue du Commandant Dumetz, 62000 Arras'),
('contact-arras-tel', 'Contact', 'arras-tel', '06 60 23 84 69'),
('contact-arras-horaires', 'Contact', 'arras-horaires', 'À COMPLÉTER — horaires d\'ouverture de l\'épicerie d\'Arras'),
('dons-carte-texte', 'Dons', 'carte-texte', 'Faites un don sécurisé par carte bancaire en quelques clics pour soutenir nos actions.'),
('dons-virement-texte', 'Dons', 'virement-texte', 'Effectuez un virement directement sur le compte de l\'association à l\'aide de nos coordonnées bancaires.'),
('dons-especes-texte', 'Dons', 'especes-texte', 'Déposez votre don en espèces directement dans nos épiceries, aux horaires d\'ouverture.'),
('don-especes-adresse', 'Don en espèces', 'adresse', '56 rue Casimir Beugnet, 62300 Lens'),
('don-especes-horaires', 'Don en espèces', 'horaires', 'À COMPLÉTER — horaires d\'accueil pour les dons en espèces'),
('don-virement-iban', 'Don par virement', 'iban', 'À COMPLÉTER — IBAN de l\'association'),
('don-virement-bic', 'Don par virement', 'bic', 'À COMPLÉTER — BIC de l\'association'),
('don-virement-banque', 'Don par virement', 'banque', 'À COMPLÉTER — nom de la banque'),
('festival-titre', 'Festival', 'titre', 'Festival solidaire'),
('festival-intro', 'Festival', 'intro', 'Un temps fort convivial et solidaire, ouvert à toutes et tous, pour célébrer le partage et le vivre-ensemble.'),
('parade-titre', 'Parade', 'titre', 'La Parade'),
('parade-intro', 'Parade', 'intro', 'Un événement festif et coloré qui rassemble habitants, bénévoles et partenaires autour de la solidarité.'),
('europalia-intro', 'Europalia', 'intro', 'L\'association participe au festival Europalia, un rendez-vous culturel qui met à l\'honneur les échanges et la diversité.'),
('europalia-festival-titre', 'Europalia', 'festival-titre', 'Le festival'),
('europalia-festival-texte', 'Europalia', 'festival-texte', 'Un programme riche mêlant spectacles, rencontres et découvertes culturelles.'),
('europalia-participation-titre', 'Europalia', 'participation-titre', 'Notre participation'),
('europalia-participation-texte', 'Europalia', 'participation-texte', 'Nous y portons les valeurs de solidarité et d\'ouverture qui animent l\'association.'),
('europalia-culture-titre', 'Europalia', 'culture-titre', 'échanges culturels'),
('europalia-culture-texte', 'Europalia', 'culture-texte', 'Des moments de partage qui créent des ponts entre les cultures et les personnes.'),
('international-intro', 'International', 'intro', 'L\'association soutient également des actions de solidarité à l\'international, en lien avec des partenaires locaux.'),
('international-niger-titre', 'International', 'niger-titre', 'Niger'),
('international-niger-texte', 'International', 'niger-texte', 'Des projets d\'aide et d\'accompagnement menés en partenariat avec des acteurs locaux.'),
('international-cameroun-titre', 'International', 'cameroun-titre', 'Cameroun'),
('international-cameroun-texte', 'International', 'cameroun-texte', 'Des initiatives solidaires pour soutenir les populations et favoriser l\'autonomie.'),
('international-echanges-titre', 'International', 'echanges-titre', 'échanges et partenariats'),
('international-echanges-texte', 'International', 'echanges-texte', 'Des collaborations durables fondées sur le respect, le partage et la réciprocité.'),
('international-cta', 'International', 'cta', 'Envie de soutenir nos actions internationales ? Contactez-nous.'),
('mentions-site', 'Mentions légales', 'site', 'À COMPLÉTER — adresse du site (ex. www.laperchetendue.fr)'),
('mentions-email', 'Mentions légales', 'email', 'À COMPLÉTER — email de contact de l\'association'),
('mentions-responsable', 'Mentions légales', 'responsable', 'À COMPLÉTER — nom du responsable de la publication'),
('mentions-hebergeur', 'Mentions légales', 'hebergeur', 'À COMPLÉTER — nom et adresse de l\'hébergeur du site');